//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rutherford.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int CustomerId { get; set; }
        public int EventId { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> CreditCardNumber { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Event Event { get; set; }
    }
}
